### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by OrjwanZaafarani** [Heldenkombinat/Logodetect#33]
I realize Logo-Net is not publicly available. However, how is it structured?

**Comment by jorgedch** [comment]
Could you please elaborate more on the title of the issue you opened? I don't see the relation between a custom dataset and the structure (do you mean the model architecture?) of Logo-Net (do you mean the trained model we use?). The model is actually publicly available. If you install Logodetect as indicated in the README, the model will be automatically downloaded in your machine in a directory as explained also in the README. You can find the architecture details in the init file in `logodetect/detectors/` and `logodetect/classifiers/`. Cheers!

**Comment by OrjwanZaafarani** [comment]
I want to train your model on a custom dataset that I have. I'm asking about the structure of the dataset that you used, did you pass it to your script as .yml file? as a.txt file? or what. Thanks for the quick reply.

**Comment by jorgedch** [comment]
Ohhh I see, thanks for the clarification. You can see the instructions for training in `/training/README.md` and the dataset conventions in `/training/loreta/datasets.py`
