### ISSUE TITLE
Logodetect does not run

### ISSUE THREAD

**Issue by nsaunier** [Heldenkombinat/Logodetect#35]
Dear authors,

I installed logodetect using pip, had a first error state that the constants package was missing, installed constants, then have the following error message:
```
> logodetect
Traceback (most recent call last):
  File "/usr/local/bin/logodetect", line 5, in <module>
    from logodetect.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/logodetect/cli.py", line 50, in <module>
    default=constants.IMAGE_FILENAME,
AttributeError: module 'constants' has no attribute 'IMAGE_FILENAME'
```

I also tried with an image as first argument and got the same error. 

Nicolas

**Comment by maxpumperla** [comment]
Dear Nicolas (@nsaunier),

We've built a new version of `logodetect`. Please run

```
pip install -U pip
pip install logodetect==1.1.2
logodetect image
```

to give it a shot.

Best,
Max
