### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by szkafander** [Heldenkombinat/Logodetect#36]
I am on Windows.

When pip installing logodetect or logodetect==1.1.2, I get 
ERROR: Could not find a version that satisfies the requirement torch>=1.9.0 (from logodetect) (from versions: none)
ERROR: No matching distribution found for torch>=1.9.0

Tried on WSL as well, got similar errors.

**Comment by jorgedch** [comment]
Thank you for your feedback @szkafander.

Good catch, the package is intended to be used in Linux and MacOS, so we'll clarify this in the documentation and setup file.
